#!/bin/bash

USRTHEMESDIR="/usr/share/themes";

function install_pkg {
	SOURCEDIR=$(pwd);
	if [ -d $SOURCEDIR ]
	then
		cd "${SOURCEDIR}";
		if [ -d "${SOURCEDIR}/themes/" ]
		then
			cd "${SOURCEDIR}/themes/"
  			sudo cp -r Eloquent "${USRTHEMESDIR}";
  			sudo find "${USRTHEMESDIR}" -type d -exec chmod 755 '{}' \;
  			sudo find "${USRTHEMESDIR}" -type f -exec chmod 644 '{}' \;
		else
			echo "Error; No Gnome / GTK theme source found."

		fi
	else
		echo "Error: No Source Found"
		echo "No source directory.Please try again later."
	fi
}

install_pkg
